<?php
$title = 'Companies';
$this->headTitle($title);

?>
<div class="rightside-data"> 
    <h3><?php echo $this->escapeHtml($title); ?></h3>
    <div class="location-language more-marbot">

        <div class="button topButton">
            <input type="button" value="Add Company" onclick="window.location='<?php echo $this->url('company', array('action' => 'add')); ?>';return false;" />       
        </div>
        <form method="post" action="">
            <div class="location-language-inn">
                <div class="account-table">
                    <table cellspacing="0px" cellpadding="0px" border="0" class="table-inn">
                        <tbody>
                            <tr>
                                <th><a class="sort" href="?column=name&order=<?php echo ($column == 'name' && $order == 'asc') ? 'desc' : 'asc'; ?>">Name</a></th>
                                <th>Address</th>
                                <th><a class="sort" href="?column=postcode&order=<?php echo ($column == 'postcode' && $order == 'asc') ? 'desc' : 'asc'; ?>">Postcode</a></th>
                                <th><a class="sort" href="?column=city&order=<?php echo ($column == 'city' && $order == 'asc') ? 'desc' : 'asc'; ?>">City</a></th>
                                <th><a class="sort" href="?column=country&order=<?php echo ($column == 'country' && $order == 'asc') ? 'desc' : 'asc'; ?>">Country</a></th>
                                <th> Action </th>
                            </tr>
                            <?php
                            $i = 0;
                             foreach ($this->paginator as $company) {
                                $i = 1 - $i;
                                $class = "row$i";
                                ?>
                                <tr id="category_row" class="<?php echo $class; ?>">  
                                    <td class="bg-gray" style="text-align:left;" ><?php echo $company->name; ?></td>
                                    <td class="bg-gray" style="text-align:left;" ><?php echo $company->address; ?></td>
                                    <td class="bg-gray" style="text-align:left;" ><?php echo $company->postcode; ?></td>
                                    <td class="bg-gray" style="text-align:left;" ><?php echo $company->city; ?></td>
                                    <td class="bg-gray" style="text-align:left;" ><?php echo $company->country->name; ?></td>
                                    <td class="bg-gray" style="text-align:left;">
                                        <div>
                                            <a href="<?php echo $this->url('company',
            array('action'=>'edit', 'id' => $company->id));?>">Edit</a> | <a href="<?php echo $this->url('company',
            array('action'=>'delete', 'id' => $company->id));?>">Delete</a> 
                                        </div>
                                    </td>
                                </tr>
                                <?php
                            }?>
                        </tbody>
                    </table>
                    <div>
                        <div class="page fr"> 
                            <div class="pagination">
                                <div class="pagination">
                                    <?php echo ( count($this->paginator) > 0 ) ? $this->paginationControl($this->paginator, 'Sliding', 'company/pager.phtml', array('url' => $this->url('company'))) : ""; ?>
                                </div>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
